# Generated by Django 4.1 on 2022-10-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_profile_image'),
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.profile'),
        ),
    ]
