# Generated by Django 4.1 on 2022-09-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='userPost',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='cation',
            new_name='caption',
        ),
    ]
