# Generated by Django 4.1 on 2022-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
