# Generated by Django 4.1 on 2022-09-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app1', '0007_alter_userpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='porfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(upload_to='images/profile_images')),
            ],
        ),
    ]
