# Generated by Django 4.1 on 2022-09-21 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_porfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='porfile',
            new_name='userporfile',
        ),
    ]
