# Generated by Django 4.1 on 2022-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_porfile_userporfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userporfile',
            name='profile_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
