# Generated by Django 4.1 on 2022-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_userporfile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userporfile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
