# Generated by Django 4.1 on 2022-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_userporfile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userporfile',
            name='profile_image',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='images'),
        ),
    ]
